---
kind: pipeline
name: default

steps:
- name: prebuild
  image: busybox
  commands:
  - sh .docker/prebuild.sh

- name: build
  image: plugins/docker
  settings:
    registry: docker.uucin.com
    username: admin
    password: Sunmap123
    repo: docker.uucin.com/zhumengyuan/operation-web
    dockerfile: .docker/Dockerfile
    auto_tag: true
    build_args:
    - version=r

trigger:
  event:
  - tag
