version: "2"
services:
  operation-web:
    image: registry.uucin.com/zhumengyuan/operation-web:dev
    restart: always
    ports:
      - 9006:80
networks:
  defaul
    ipam:
      config:
        - subnet: 172.20.139.0/24
